--- GNUmakefile	2006-12-06 05:40:55.000000000 +0300
+++ bin/GNUmakefile	2008-03-28 10:58:07.000000000 +0300
@@ -124,10 +124,10 @@
 	$(CXX) -shared -fPIC -o $@ $(OSGART_OBJECTS) $(LDFLAGS) $(____DEBUG_4) -L$(ARTOOLKIT_PATH)/lib/
 
 osgart_example: $(OSGART_EXAMPLE_OBJECTS) libosgART.so
-	$(CXX) -o $@ $(OSGART_EXAMPLE_OBJECTS) $(LDFLAGS)   libosgART.so -losg -losgDB -losgProducer -lProducer
+	$(CXX) -o $@ $(OSGART_EXAMPLE_OBJECTS) $(LDFLAGS)   libosgART.so -losg -losgDB -losgViewer
 
 osgart_artoolkit.so: $(OSGART_ARTOOLKIT_OBJECTS) libosgART.so
-	$(CXX) -shared -fPIC -o $@ $(OSGART_ARTOOLKIT_OBJECTS) $(LDFLAGS) -L$(ARTOOLKIT_PATH)/lib/  libosgART.so -lARvideo -losg
+	$(CXX) -shared -fPIC -o $@ $(OSGART_ARTOOLKIT_OBJECTS) $(LDFLAGS) -L$(ARTOOLKIT_PATH)/lib/  libosgART.so -lARvideo -losg -ldc1394_control
 
 osgart_artoolkit_tracker.so: $(OSGART_ARTOOLKIT_TRACKER_OBJECTS) libosgART.so
 	$(CXX) -shared -fPIC -o $@ $(OSGART_ARTOOLKIT_TRACKER_OBJECTS) $(LDFLAGS) -L$(ARTOOLKIT_PATH)/lib/  libosgART.so -losg -lARgsub_lite -lAR -lARMulti
